version: '2.2'

services:
  nutritionapiapp:
    image: nutritionapi
    container_name: nutritionapiapp
    depends_on:
      - nutritionmongodb
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 8080
    ports:
      - 7070:8080
    networks:
      - nutritionbridgenetwork
    restart: always


  

networks:
  nutritionbridgenetwork:
    name: exercises-api_mongobridgenetwork 
    external: true

volumes:
  mymongovolume:
